name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: NBA
      uses: Alexmry/My-Favorite-NBA-Player

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        APPLICATIONID: ${{ secrets.APPLICATIONID }}
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
